auth:
  db:
    image: postgres:13
    password: password
  enabled: true
  image:
    repository: changsiuuuu/jit-hub-auth
    tag: latest
  replicaCount: 1
  service:
    port: 8000
gateway:
  enabled: true
  image:
    repository: changsiuuuu/jit-hub-gateway
    tag: latest
  replicaCount: 1
  service:
    port: 80
ingressRule:
  host: leechs.shop
  namespace: jit-hub
tourist:
  db:
    image: postgres:13
    password: password
  enabled: true
  image:
    repository: changsiuuuu/jit-hub-tourist
    tag: latest
  replicaCount: 1
  service:
    port: 8000
traffic:
  db:
    image: postgres:13
    password: password
  enabled: true
  image:
    repository: changsiuuuu/jit-hub-traffic
    tag: latest
  replicaCount: 1
  service:
    port: 8000
weather:
  db:
    image: postgres:13
    password: password
  enabled: true
  image:
    repository: changsiuuuu/jit-hub-weather
    tag: latest
  replicaCount: 1
  service:
    port: 8000
