# gitops/values/eks-a/ops-values.yaml

# nodepool.yaml에서 {{ .Values.environment }}로 참조
environment: eks-a

clusterName: eks-a

keda:
  enabled: true

  # ScaledObject가 생성될 네임스페이스
  # 대상 Deployment와 같은 네임스페이스여야 합니다.
  namespace: jit-hub

  minReplicaCount: 3
  maxReplicaCount: 10

  # 부하가 감소한 후 축소하기까지 기다리는 시간(초)
  cooldownPeriod: 300

  # Prometheus 쿼리 결과가 이 값을 기준으로 스케일링됩니다.
  threshold: "50"

  # kube-prometheus-stack의 Prometheus 서비스 주소
  serverAddress: >-
    http://eks-a-monitoring-stack-kube-prometheus.monitoring.svc.cluster.local:9090

karpenter:
  enabled: true

  namespace: karpenter

  nodePoolName: eks-a-nodepool
  nodeClassName: eks-a-nodeclass

  iamRole: KarpenterNodeRole-eks-a

  # Karpenter가 생성할 수 있는 EC2 인스턴스 유형
  instanceTypes:
    - t3.small   # vCPU 2, Memory 2GiB
    - t3.medium  # vCPU 2, Memory 4GiB
    - t3.large   # vCPU 2, Memory 8GiB

  # EC2 구매 방식
  capacityTypes:
    - on-demand

  # NodePool 전체 리소스 최대치
  limits:
    cpu: "100"
    memory: "100Gi"

  # 노드 최적화 및 비용 절감 설정
  disruption:
    # WhenEmpty: Pod가 없는 노드만 정리
    # WhenEmptyOrUnderutilized: 비어 있거나 사용률이 낮은 노드 정리
    consolidationPolicy: WhenEmpty

    # 노드가 빈 상태가 된 후 종료하기까지 기다리는 시간
    consolidateAfter: 30s

    # 노드 최대 수명
    expireAfter: 720h

  ebs:
    volumeSize: 100Gi
    volumeType: gp3

customScheduler:
  enabled: true