# On-Prem 클러스터 전용 Override Values
# Umbrella Chart (Subchart) 구조에 맞게 작성

ingressRule:
  namespace: "jit-hub"
  host: "leechs.shop"

gateway:
  replicaCount: 1
  image:
    repository: "changsiuuuu/jit-hub-gateway"
    tag: "latest"

auth:
  replicaCount: 1
  image:
    repository: "changsiuuuu/jit-hub-auth"
    tag: "latest"

weather:
  replicaCount: 1
  image:
    repository: "changsiuuuu/jit-hub-weather"
    tag: "latest"

traffic:
  replicaCount: 1
  image:
    repository: "changsiuuuu/jit-hub-traffic"
    tag: "latest"

tourist:
  replicaCount: 1
  image:
    repository: "changsiuuuu/jit-hub-tourist"
    tag: "latest"
